name: 'Setup PHP-environment'
description: 'Sets up PHP, Node, and dependencies'

inputs:
  php-version:
    required: true
    default: '8.4'
    description: 'PHP version to use'

runs:
  using: composite
  steps:
    - name: Get Composer Cache Directory
      shell: bash
      id: composer-cache
      run: echo "dir=$(composer config cache-files-dir)" >> $GITHUB_OUTPUT

    - name: Cache composer dependencies
      uses: actions/cache@v4
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ github.job }}-${{ hashFiles('**/composer.json') }}
        restore-keys: |
          ${{ runner.os }}-composer-${{ github.job }}-
          ${{ runner.os }}-composer-

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        tools: composer:v2
        coverage: none

    - name: Install Composer dependencies
      shell: bash
      run: |
        composer install --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist --optimize-autoloader
