name: Continuous integration

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
  push:
    branches:
      - main

env:
  PHP_VERSION: '8.4'

jobs:
  composer-validate:
    name: Run composer validate
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure environment
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Validate composer.json
        run: composer validate --strict

      - name: Check namespaces
        run: composer dump-autoload --optimize --strict-psr

  analyse:
    name: Run analyse script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Cache PHPStan
        uses: actions/cache@v4
        with:
          path: /tmp/phpstan
          key: ${{ runner.os }}-phpstan-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-phpstan-

      - run: |
          mkdir -p /tmp/phpstan

      - name: Run PHPStan
        run: composer analyse:ci

  format:
    name: Run format script
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}

      - name: Cache Rector objects
        uses: actions/cache@v4
        with:
          path: /tmp/rector
          key: ${{ runner.os }}-rector-${{ github.run_id }}
          restore-keys: ${{ runner.os }}-rector-

      - run: mkdir -p /tmp/rector

      - name: Run Rector
        run: composer format:ci

  test:
    name: Run test script
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure environment
        uses: ./.github/actions/setup-php
        with:
          php-version: ${{ env.PHP_VERSION }}
          
      - name: Test with phpunit
        run: composer test
